# version: '3'
# services:
#   mongo:
#     image: mongo:latest
#     container_name: mongo
#     ports:
#       - 27017:27017
#   nginx:
#     image: nginx:latest
#     container_name: nginx
#     ports:
#       - 8888:80
#     restart: always
#   mitmproxyutil:
#     build: ./mitmproxyutil
#     container_name: mitmproxyutil
#     ports:
#       - 8088:8080
#     restart: always
#     volumes:
#       - ./mitmproxyutil/mitmproxyutil.py:/mitmproxyutil.py
#       - ./mitmproxyutil/mitmproxyutil.log:/mitmproxyutil.log
#   hard-disk-monitoring:
#     build: ./hard-disk-monitoring
#     container_name: hard-disk-monitoring
#     restart: always
#     volumes:
#       - /Users/weizongtang/server/docker/hard-disk-monitoring:/hard-disk-monitoring
#       - /Users/weizongtang/Public/test:/syn/test
#       - /Users/weizongtang/Public/server:/syn/server
#       - /Users/weizongtang/Documents/笔记:/syn/笔记
#       - /Users/weizongtang/logs/hard-disk-monitoring:/logs

version: '3'
services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "666666WW"
      MYSQL_USER: 'test'
      MYSQL_PASS: '666666WW'
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./mysql/conf:/etc/mysql/mysql.conf.d
      - ./mysql/db:/db
      - ./mysql/binlog:/data/binlog
      - ./mysql/log/mysql.log:/data/log/mysql.log
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --port 6379 --requirepass 123456  --appendonly yes
    restart: always
  rocketmq:
    image: java:8
    container_name: rocketmq
    ports:
      - 9876:9876
    restart: always
    tty: true
    volumes:
      - ./rocketmq:/rocketmq
    working_dir: /rocketmq
    entrypoint:
      - /rocketmq/start.sh

