mongoimport --db pangu --collection QRTZ_BLOB_TRIGGERS --type csv --headerline --file /db/QRTZ_BLOB_TRIGGERS.csv
mongoimport --db pangu --collection QRTZ_CALENDARS --type csv --headerline --file /db/QRTZ_CALENDARS.csv
mongoimport --db pangu --collection QRTZ_CRON_TRIGGERS --type csv --headerline --file /db/QRTZ_CRON_TRIGGERS.csv
mongoimport --db pangu --collection QRTZ_FIRED_TRIGGERS --type csv --headerline --file /db/QRTZ_FIRED_TRIGGERS.csv
mongoimport --db pangu --collection QRTZ_JOB_DETAILS --type csv --headerline --file /db/QRTZ_JOB_DETAILS.csv
mongoimport --db pangu --collection QRTZ_LOCKS --type csv --headerline --file /db/QRTZ_LOCKS.csv
mongoimport --db pangu --collection QRTZ_PAUSED_TRIGGER_GRPS --type csv --headerline --file /db/QRTZ_PAUSED_TRIGGER_GRPS.csv
mongoimport --db pangu --collection QRTZ_SCHEDULER_STATE --type csv --headerline --file /db/QRTZ_SCHEDULER_STATE.csv
mongoimport --db pangu --collection QRTZ_SIMPLE_TRIGGERS --type csv --headerline --file /db/QRTZ_SIMPLE_TRIGGERS.csv
mongoimport --db pangu --collection QRTZ_SIMPROP_TRIGGERS --type csv --headerline --file /db/QRTZ_SIMPROP_TRIGGERS.csv
mongoimport --db pangu --collection QRTZ_TRIGGERS --type csv --headerline --file /db/QRTZ_TRIGGERS.csv
mongoimport --db pangu --collection code_dictionary --type csv --headerline --file /db/code_dictionary.csv
mongoimport --db pangu --collection schedule_job --type csv --headerline --file /db/schedule_job.csv
mongoimport --db pangu --collection schedule_job_log --type csv --headerline --file /db/schedule_job_log.csv
mongoimport --db pangu --collection sys_config --type csv --headerline --file /db/sys_config.csv
mongoimport --db pangu --collection sys_dept --type csv --headerline --file /db/sys_dept.csv
mongoimport --db pangu --collection sys_dict --type csv --headerline --file /db/sys_dict.csv
mongoimport --db pangu --collection sys_log --type csv --headerline --file /db/sys_log.csv
mongoimport --db pangu --collection sys_menu --type csv --headerline --file /db/sys_menu.csv
mongoimport --db pangu --collection sys_menu_20191107 --type csv --headerline --file /db/sys_menu_20191107.csv
mongoimport --db pangu --collection sys_oss --type csv --headerline --file /db/sys_oss.csv
mongoimport --db pangu --collection sys_role --type csv --headerline --file /db/sys_role.csv
mongoimport --db pangu --collection sys_role_dept --type csv --headerline --file /db/sys_role_dept.csv
mongoimport --db pangu --collection sys_role_menu --type csv --headerline --file /db/sys_role_menu.csv
mongoimport --db pangu --collection sys_role_menu_20191107 --type csv --headerline --file /db/sys_role_menu_20191107.csv
mongoimport --db pangu --collection sys_user --type csv --headerline --file /db/sys_user.csv
mongoimport --db pangu --collection sys_user_extend --type csv --headerline --file /db/sys_user_extend.csv
mongoimport --db pangu --collection sys_user_role --type csv --headerline --file /db/sys_user_role.csv
mongoimport --db pangu --collection tb_token --type csv --headerline --file /db/tb_token.csv
mongoimport --db pangu --collection tb_user --type csv --headerline --file /db/tb_user.csv
mongoimport --db pangu --collection tb_user_20191107 --type csv --headerline --file /db/tb_user_20191107.csv
mongoimport --db pangu --collection tu_master_partner --type csv --headerline --file /db/tu_master_partner.csv
mongoimport --db pangu --collection wk_activity --type csv --headerline --file /db/wk_activity.csv
mongoimport --db pangu --collection wk_activity_image --type csv --headerline --file /db/wk_activity_image.csv
mongoimport --db pangu --collection wk_activity_remove_back --type csv --headerline --file /db/wk_activity_remove_back.csv
mongoimport --db pangu --collection wk_admin_roles --type csv --headerline --file /db/wk_admin_roles.csv
mongoimport --db pangu --collection wk_admin_roles_rules --type csv --headerline --file /db/wk_admin_roles_rules.csv
mongoimport --db pangu --collection wk_admin_rules --type csv --headerline --file /db/wk_admin_rules.csv
mongoimport --db pangu --collection wk_admins --type csv --headerline --file /db/wk_admins.csv
mongoimport --db pangu --collection wk_admins_roles --type csv --headerline --file /db/wk_admins_roles.csv
mongoimport --db pangu --collection wk_ads --type csv --headerline --file /db/wk_ads.csv
mongoimport --db pangu --collection wk_ads_detail --type csv --headerline --file /db/wk_ads_detail.csv
mongoimport --db pangu --collection wk_audit --type csv --headerline --file /db/wk_audit.csv
mongoimport --db pangu --collection wk_code_library --type csv --headerline --file /db/wk_code_library.csv
mongoimport --db pangu --collection wk_feedback --type csv --headerline --file /db/wk_feedback.csv
mongoimport --db pangu --collection wk_files --type csv --headerline --file /db/wk_files.csv
mongoimport --db pangu --collection wk_materiel --type csv --headerline --file /db/wk_materiel.csv
mongoimport --db pangu --collection wk_order --type csv --headerline --file /db/wk_order.csv
mongoimport --db pangu --collection wk_order_20191107 --type csv --headerline --file /db/wk_order_20191107.csv
mongoimport --db pangu --collection wk_order_ads --type csv --headerline --file /db/wk_order_ads.csv
mongoimport --db pangu --collection wk_order_ads_detail --type csv --headerline --file /db/wk_order_ads_detail.csv
mongoimport --db pangu --collection wk_order_detail_bak --type csv --headerline --file /db/wk_order_detail_bak.csv
mongoimport --db pangu --collection wk_order_remove_back --type csv --headerline --file /db/wk_order_remove_back.csv
mongoimport --db pangu --collection wk_order_status_log --type csv --headerline --file /db/wk_order_status_log.csv
mongoimport --db pangu --collection wk_sms_log --type csv --headerline --file /db/wk_sms_log.csv
