version: '3'
services:
  mysql:
    image: mysql:8.0.23
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "666666WW"
      MYSQL_USER: 'test'
      MYSQL_PASS: '666666WW'
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./config:/etc/mysql
      - ./db:/db
      - ./binlog:/data/binlog
      - ./log/mysql.log:/data/log/mysql.log