version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    command: redis-server --port 6379 --requirepass 123456  --appendonly yes
    restart: always